### ISSUE TITLE
stream.push() after EOF

### ISSUE THREAD

**Issue by 404invalid-user** [404invalid-user/redbased#2]
full error:
```
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
    at readableAddChunkPushObjectMode (node:internal/streams/readable:522:28)
    at Readable.push (node:internal/streams/readable:391:5)
    at SchemaInstance.<anonymous> (C:\Users\invaliduser\Documents\GitHub\redbased\dist\SchemaInstance.js:207:64)
    at step (C:\Users\invaliduser\Documents\GitHub\redbased\dist\SchemaInstance.js:33:23)
    at Object.next (C:\Users\invaliduser\Documents\GitHub\redbased\dist\SchemaInstance.js:14:53)
    at C:\Users\invaliduser\Documents\GitHub\redbased\dist\SchemaInstance.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\invaliduser\Documents\GitHub\redbased\dist\SchemaInstance.js:4:12)
    at ScanStream.handleRedisStreamData (C:\Users\invaliduser\Documents\GitHub\redbased\dist\SchemaInstance.js:172:77)
    at ScanStream.emit (node:events:519:28) {
  code: 'ERR_STREAM_PUSH_AFTER_EOF'
}
```

**Comment by 404invalid-user** [comment]
i think [85504da](https://github.com/404invalid-user/redbased/commit/85504dabaa3d21ba892f2b88cc69261d7ff776cd) fixed it but will require more testing. it doesn't happen all the time
